/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bombbomb) {
      root.Bombbomb = {};
    }
    root.Bombbomb.PromptSocialPrompt = factory(root.Bombbomb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PromptSocialPrompt model module.
   * @module model/PromptSocialPrompt
   * @version 2.0.25798
   */

  /**
   * Constructs a new <code>PromptSocialPrompt</code>.
   * The Prompt\\SocialPrompt class
   * @alias module:model/PromptSocialPrompt
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>PromptSocialPrompt</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PromptSocialPrompt} obj Optional instance to populate.
   * @return {module:model/PromptSocialPrompt} The populated <code>PromptSocialPrompt</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('jerichoId')) {
        obj['jerichoId'] = ApiClient.convertToType(data['jerichoId'], 'String');
      }
      if (data.hasOwnProperty('promptSubject')) {
        obj['promptSubject'] = ApiClient.convertToType(data['promptSubject'], 'String');
      }
      if (data.hasOwnProperty('promptHtml')) {
        obj['promptHtml'] = ApiClient.convertToType(data['promptHtml'], 'String');
      }
      if (data.hasOwnProperty('scheduledSendDate')) {
        obj['scheduledSendDate'] = ApiClient.convertToType(data['scheduledSendDate'], 'Date');
      }
      if (data.hasOwnProperty('clientGroupId')) {
        obj['clientGroupId'] = ApiClient.convertToType(data['clientGroupId'], 'String');
      }
      if (data.hasOwnProperty('thumbnailUrl')) {
        obj['thumbnailUrl'] = ApiClient.convertToType(data['thumbnailUrl'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Number');
      }
      if (data.hasOwnProperty('createdDate')) {
        obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
      }
      if (data.hasOwnProperty('lastNotified')) {
        obj['lastNotified'] = ApiClient.convertToType(data['lastNotified'], 'Date');
      }
      if (data.hasOwnProperty('sendMechanism')) {
        obj['sendMechanism'] = ApiClient.convertToType(data['sendMechanism'], 'Date');
      }
      if (data.hasOwnProperty('sendTypes')) {
        obj['sendTypes'] = ApiClient.convertToType(data['sendTypes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The identifier of the prompt. Read Only.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The prompt's owner. Read Only.
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * If sent in a jericho context, this will have the jericho id
   * @member {String} jerichoId
   */
  exports.prototype['jerichoId'] = undefined;
  /**
   * The prompt's subject line
   * @member {String} promptSubject
   */
  exports.prototype['promptSubject'] = undefined;
  /**
   * The suggested script of the prompt.
   * @member {String} promptHtml
   */
  exports.prototype['promptHtml'] = undefined;
  /**
   * When the final email is scheduled to be sent
   * @member {Date} scheduledSendDate
   */
  exports.prototype['scheduledSendDate'] = undefined;
  /**
   * The client group campaign that created the prompt.
   * @member {String} clientGroupId
   */
  exports.prototype['clientGroupId'] = undefined;
  /**
   * The URL of a thumbnail image for this prompt
   * @member {String} thumbnailUrl
   */
  exports.prototype['thumbnailUrl'] = undefined;
  /**
   * The status of the prompt: created = 0, sent = 10, recorded = 20, job_created = 30, timed_out = 40, declined = 50 Read Only
   * @member {Number} status
   */
  exports.prototype['status'] = undefined;
  /**
   * When the email was first sent out
   * @member {Date} createdDate
   */
  exports.prototype['createdDate'] = undefined;
  /**
   * When the user was last notified about a prompt email waiting for a video
   * @member {Date} lastNotified
   */
  exports.prototype['lastNotified'] = undefined;
  /**
   * The sendMechanism property
   * @member {Date} sendMechanism
   */
  exports.prototype['sendMechanism'] = undefined;
  /**
   * The types of mechanisms this prompt can send.
   * @member {Array.<String>} sendTypes
   */
  exports.prototype['sendTypes'] = undefined;



  return exports;
}));


