/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bombbomb) {
      root.Bombbomb = {};
    }
    root.Bombbomb.VideoEncodingStatusResponse = factory(root.Bombbomb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VideoEncodingStatusResponse model module.
   * @module model/VideoEncodingStatusResponse
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>VideoEncodingStatusResponse</code>.
   * The VideoEncodingStatusResponse class
   * @alias module:model/VideoEncodingStatusResponse
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>VideoEncodingStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VideoEncodingStatusResponse} obj Optional instance to populate.
   * @return {module:model/VideoEncodingStatusResponse} The populated <code>VideoEncodingStatusResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('isReady')) {
        obj['isReady'] = ApiClient.convertToType(data['isReady'], 'Boolean');
      }
      if (data.hasOwnProperty('isFailed')) {
        obj['isFailed'] = ApiClient.convertToType(data['isFailed'], 'Boolean');
      }
      if (data.hasOwnProperty('progress')) {
        obj['progress'] = ApiClient.convertToType(data['progress'], 'Integer');
      }
    }
    return obj;
  }

  /**
   * Returns true if the video is done encoding and finalized.
   * @member {Boolean} isReady
   */
  exports.prototype['isReady'] = undefined;
  /**
   * Returns true if the video encoding process failed.
   * @member {Boolean} isFailed
   */
  exports.prototype['isFailed'] = undefined;
  /**
   * 0-100 value indicating progress of video encoding process.
   * @member {Integer} progress
   */
  exports.prototype['progress'] = undefined;



  return exports;
}));


