/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BombbombNodejsOpenapi);
  }
}(this, function(expect, BombbombNodejsOpenapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BombbombNodejsOpenapi.JerichoPerformance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JerichoPerformance', function() {
    it('should create an instance of JerichoPerformance', function() {
      // uncomment below and update the code to test JerichoPerformance
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be.a(BombbombNodejsOpenapi.JerichoPerformance);
    });

    it('should have the property sent (base name: "sent")', function() {
      // uncomment below and update the code to test the property sent
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property uniqueViews (base name: "uniqueViews")', function() {
      // uncomment below and update the code to test the property uniqueViews
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property uniqueLandingPageViews (base name: "uniqueLandingPageViews")', function() {
      // uncomment below and update the code to test the property uniqueLandingPageViews
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property landingPageViews (base name: "landingPageViews")', function() {
      // uncomment below and update the code to test the property landingPageViews
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property bounce (base name: "bounce")', function() {
      // uncomment below and update the code to test the property bounce
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property open (base name: "open")', function() {
      // uncomment below and update the code to test the property open
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property click (base name: "click")', function() {
      // uncomment below and update the code to test the property click
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property videoPlay (base name: "videoPlay")', function() {
      // uncomment below and update the code to test the property videoPlay
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property abuseComplaints (base name: "abuseComplaints")', function() {
      // uncomment below and update the code to test the property abuseComplaints
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

    it('should have the property contacts (base name: "contacts")', function() {
      // uncomment below and update the code to test the property contacts
      //var instane = new BombbombNodejsOpenapi.JerichoPerformance();
      //expect(instance).to.be();
    });

  });

}));
