/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BombbombNodejsOpenapi);
  }
}(this, function(expect, BombbombNodejsOpenapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BombbombNodejsOpenapi.OAuthClient();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OAuthClient', function() {
    it('should create an instance of OAuthClient', function() {
      // uncomment below and update the code to test OAuthClient
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be.a(BombbombNodejsOpenapi.OAuthClient);
    });

    it('should have the property identifier (base name: "identifier")', function() {
      // uncomment below and update the code to test the property identifier
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

    it('should have the property clientSecret (base name: "clientSecret")', function() {
      // uncomment below and update the code to test the property clientSecret
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

    it('should have the property grantsAllowed (base name: "grantsAllowed")', function() {
      // uncomment below and update the code to test the property grantsAllowed
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

    it('should have the property owningUserId (base name: "owningUserId")', function() {
      // uncomment below and update the code to test the property owningUserId
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

    it('should have the property redirectUri (base name: "redirectUri")', function() {
      // uncomment below and update the code to test the property redirectUri
      //var instane = new BombbombNodejsOpenapi.OAuthClient();
      //expect(instance).to.be();
    });

  });

}));
