/**
 * BombBomb
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.831
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bombbomb);
  }
}(this, function(expect, Bombbomb) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bombbomb.PromptMonthlyPerformance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PromptMonthlyPerformance', function() {
    it('should create an instance of PromptMonthlyPerformance', function() {
      // uncomment below and update the code to test PromptMonthlyPerformance
      //var instane = new Bombbomb.PromptMonthlyPerformance();
      //expect(instance).to.be.a(Bombbomb.PromptMonthlyPerformance);
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new Bombbomb.PromptMonthlyPerformance();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instane = new Bombbomb.PromptMonthlyPerformance();
      //expect(instance).to.be();
    });

    it('should have the property userBatchListsIdHelper (base name: "userBatchListsIdHelper")', function() {
      // uncomment below and update the code to test the property userBatchListsIdHelper
      //var instane = new Bombbomb.PromptMonthlyPerformance();
      //expect(instance).to.be();
    });

    it('should have the property promptIdHelper (base name: "promptIdHelper")', function() {
      // uncomment below and update the code to test the property promptIdHelper
      //var instane = new Bombbomb.PromptMonthlyPerformance();
      //expect(instance).to.be();
    });

  });

}));
